# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_auto_20180518_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='driver/profile-pic')),
                ('car_image', models.ImageField(blank=True, upload_to='car-image/')),
                ('car_capacity', models.PositiveIntegerField(blank=True, default=0)),
                ('car_number_plate', models.CharField(blank=True, max_length=255)),
                ('car_color', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='driver',
            name='image',
        ),
        migrations.AddField(
            model_name='driver',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='driver.Driver'),
        ),
    ]
