# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_auto_20180518_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='driver',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='DriverProfile',
        ),
    ]
