# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0006_auto_20180518_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='avatar',
        ),
        migrations.AddField(
            model_name='driver',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
