# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-20 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0009_driver_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='point',
            unique_together=set([('latitude', 'longitude')]),
        ),
    ]
