# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0002_passenger_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='bio',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='passenger',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
